/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  FooElement as FooElement
} from './components/foo-element/foo-element';

declare global {
  interface HTMLFooElementElement extends FooElement, HTMLElement {
  }
  var HTMLFooElementElement: {
    prototype: HTMLFooElementElement;
    new (): HTMLFooElementElement;
  };
  interface HTMLElementTagNameMap {
    "foo-element": HTMLFooElementElement;
  }
  interface ElementTagNameMap {
    "foo-element": HTMLFooElementElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "foo-element": JSXElements.FooElementAttributes;
    }
  }
  namespace JSXElements {
    export interface FooElementAttributes extends HTMLAttributes {
      
    }
  }
}

